# System information

function(update_file path content)
    set(old_content "")
    if(EXISTS "${path}")
        file(READ "${path}" old_content)
    endif()
    if(NOT old_content STREQUAL content)
        file(WRITE "${path}" "${content}")
    endif()
endfunction(update_file)

function(update_deps_file deps)
    set(deps_file "CMakeDeps.cmake")
    list(REMOVE_DUPLICATES deps)
    foreach(dep IN LISTS deps)
        file(RELATIVE_PATH rel_dep ${CMAKE_CURRENT_SOURCE_DIR} ${dep})
        list(APPEND rel_deps ${rel_dep})
    endforeach(dep)
    list(SORT rel_deps)
    # Update the deps file
    set(content "# generated by make process\nset(src_files ${rel_deps})\n")
    update_file(${deps_file} "${content}")
    include(${deps_file})
endfunction(update_deps_file)

message("-- The System identification is ${CMAKE_SYSTEM} | ${CMAKE_SYSTEM_NAME} | ${CMAKE_SYSTEM_VERSION} | ${CMAKE_SYSTEM_INFO_FILE}")
